### ISSUE TITLE
乐视的tkey

### ISSUE THREAD

**Issue by icemy** [yhsj0919/VideoParse#2]
乐视tkey貌似不对啊，返回statuscode：1003

**Comment by yhsj0919** [comment]
tkey没问题，现在不知道什么原因，有一定几率失败，换流量就没问题了.  ^(T-T)^ ,也或者是真有问题，没发现，我现在遇到的问题是间歇性的，不太好定位

**Comment by yhsj0919** [comment]
已经重构
