### ISSUE TITLE
youku，腾讯解析失败

### ISSUE THREAD

**Issue by xiaosong520** [yhsj0919/VideoParse#5]
下载demo测试了一下,发现：
youku解析返回数据里面提示该视频已被屏蔽，url获取不到，但是视频标题还是有的；
qq解析则导致APP直接crash了。作者有联系方式吗？ 想找你私聊讨论一下。

**Comment by xiaosong520** [comment]
@yhsj0919  关于QQ视频解析的问题，调试发现是在 QQ.kt  的120 行那个for (part in 1..100)循环中导致 catch 了 ，调试是只有五分钟的url，这个问题是否是由于url字符串拼接超时导致的？

**Comment by yhsj0919** [comment]
能提供一下播放地址么,有一部分的确会失败,这是个测试项目,还没有做完整的错误提示

**Comment by xiaosong520** [comment]
@yhsj0919   找到问题了， 是 return 语句有误，没有实例化实体对象。

**Comment by xiaosong520** [comment]
@yhsj0919 播放地址就是demo里面的url ，我没改地址。

**Comment by yhsj0919** [comment]
qq的那个肯定会catch,暂时就是那么处理的..原因是不知道他有多少切片....

**Comment by xiaosong520** [comment]
@yhsj0919  好的，我自己试试完善一下QQ的解析逻辑，能留个QQ 联系吗？ 最近项目赶着要用腾讯的视频，有问题向你请问讨论就方便点~

**Comment by yhsj0919** [comment]
1130402124

**Comment by yhsj0919** [comment]
@xiaosong520 刚才看了一下,那两个解析都没问题,优酷的是因为我只打印了视频名字,腾讯的也没问题(5分钟怀疑是vip),腾讯我没有区分清晰度,至于那个catch不要在意,还有就是这俩网站视频是分段的,有点麻烦,别的网站大部分都是m3u8的直播流,处理起来比较简单
